Rfm-1
OpenTeens/community pull request #12
Opened 2024-07-24 14:00 UTC by BernieHuang2008

2024-07-24 14:07 UTC, cxzlw commented on RequestForMoney/1/request.md
> +部门负责人：
```suggestion
部门负责人：王思诚
```

2024-07-24 14:08 UTC, cxzlw requested changes

2024-07-24 14:09 UTC, cxzlw approved these changes

2024-07-24 14:09 UTC, cxzlw commented
lgtm

2024-07-26 13:41 UTC, mishmichmeng commented on RequestForMoney/1/request.md
> +经费审批人：
经费审批人：孟思言

2024-07-26 13:49 UTC, mishmichmeng commented on RequestForMoney/1/request.md
> +经费审批人：
```suggestion
经费审批人：孟思言
```

2024-07-26 13:50 UTC, mishmichmeng commented on RequestForMoney/1/request.md
> +审批时间：
```suggestion
审批时间：2024/07/26 21：50
```

2024-07-26 14:08 UTC, BernieHuang2008 commented
@mishmichmeng 下次顺便给个approval

2024-07-26 14:13 UTC, merged